plugin = ~/.config/hypr/plugins/hyperrotation.so

plugin:rotation:output = DSI-1
plugin:rotation:mode = 1080x2340@60
plugin:rotation:position = 0x0
plugin:rotation:scale = 1
plugin:rotation:touch_transform = -1
plugin:rotation:mute_notifications = 0

bind = SUPER, R, plugin:rotation:right
bind = SUPER SHIFT, R, plugin:rotation:normal
